/**
 * Static content for Jury.jsx / JuryHeader.jsx (formerly Sanity document
 * `juryPage`). Frozen from the live CDN content — see migration notes in
 * src/content/homePhases.js for context.
 */
export const juryPage = {
  tag: { en: 'Meet the jury', fr: 'Rencontrez le jury' },
  title: { en: 'Festival Jury', fr: 'Jury du Festival' },
  festivalName: 'MARSAI',
  description: {
    en: 'Discover the exceptional experts who evaluate your creations generated by artificial intelligence.',
    fr: "Découvrez les experts d'exception qui évaluent vos créations générées par l'intelligence artificielle.",
  },
};
